### ISSUE TITLE
Fix current schema Issues

### ISSUE THREAD

**Issue by SaumyaKhati** [GauravTalreja/ebb#32]
Current issues found while adding sample data. Adding it here so that we have a easy-to-find record.
-  We've currently defined `external_id` to be unique for _courses_, but cross-listed courses have this value in common. So it cannot be unique if we want to be able to insert cross-listed queries.
- The `catalog_number` attribute cannot be an int because for some courses, it can include a character. For ex:`ENGL 306D` where the catalog number is the latter word.
-  As discussed, for academic level, it might be better to use the same val as OpenData Api. They use `UG` (Undergraudate) or `GRD` (Graduate).
- For the `max_enrollment/current_enrollment` attributes of `course_offerings`, are we only counting the enrollment wrt/ LEC type of sections? Or are we just summing all of the section/schedules values and then presenting the **total** values as the "offering's" enrollment quota. Because if we just use LEC, then this may not be universal since some courses don't have such a component.
- As @GauravTalreja mentioned, it's more readable to do 7 columns for days of the week when a class section/schedule is active rather than the string encoding. 
- For `prerequisites_id`, should this be referring to the `prerequisites(id)`? Otherwise, how is this value defined @Justin-Kwan?

**Comment by Justin-Kwan** [comment]
Thanks for taking a look here! If `external_id` cannot be unique, we can probably remove the constraint on it since courses can use the PK serial id too.

Good catch for `catalog_number`! Let's make it varchar or text then?

Not too opinionated on `UG` or `undergrad`. Let's go `UG` to keep it consistent then.

For `course_offerings` max enrollment, I believe that should be across all offerings, we can just copy the value outputted by the API which already aggregates it.

Yep, agree! Let's go with multiple columns per day and we can construct SQL query in Rust to append more conditions per day(s).

Course table `prerequisites_id` is a FK that does reference `prerequisites(id)`, however it can be null since a course may not have prereqs.

**Comment by GauravTalreja** [comment]
Please continue the discussion in #13
